FROM    mcr.microsoft.com/devcontainers/rust:1-1-bookworm

RUN     apt update && apt upgrade -y && apt install nodejs npm iputils-ping nmap -y

#RUN     apt install transmission transmission-daemon mitmproxy -y